wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702272567.216978
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.8.8
      5: 0.16.1
      6: 4.35.0
      8:
      - 5
      13: linux-x86_64
